export const scaleFactor = 4;

export const dialogueData = {
  pc: "THIS IS THE THERAPY CORNER. WHERE YOU TALK TO GPT TO RESOLVE ALL YOUR ISSUES. YOU CAN TALK TO US FAM, I'LL GIVE WAY BETTER ADVICE THAN SOME STUPID CLANKER.",
  "cs-degree": "THIS IS THE CARD I MADE YOU, YOU HAVE IT FRAMED ON THE WALL CAUSE IT'S SO GREAT. BEST GIFT EVER.",
  "sofa-table": "THAT'S YOUR SOFA. THIS IS WHERE THE BARBIE DOLL INCIDENT OCCURED",
  tv: "TV: REMEMBER WHEN WE ALL SAT AND WATCHED DONT BREATHE (YALL SHIT YOURSELF OUT OF FEAR). THE SAME TV WITNESSED THE BEST DANCE MOVES WHEN WE PLAYED WII. ALSO PEAK MARIO KART 4-WAY SPLIT SCREEN GAMES. RED SHELL INCOMING.",
  bed: "THIS IS WHERE THE LADY BED ROTS. SCROLLING THROUGH REELS PRETENDING TO BE PRODUCTIVE.",
  resume: "THANKS FOR BEING THE BESTEST FRIEND YOU LOSER",
  projects: "GREEK RESTRAUNT IN THE MAKING RN. LET'S ALL BE RICH TOGETHER FR FR",
  library: "YOU DONT READ, THIS IS JUST HERE FOR AESTHETICS. START READING SOME BOOKS OR YOULL BE STUPID FOREVER.",
  exit: "DON'T LEAVE. (GET IT? DON'T BREATHE). HE HE HE. "
};
